version: '3.5'

services:
  db:
    image: postgres
    restart: always
    container_name: chat-postgres
    environment:
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME_DB}
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - '5433:5432'

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: chat-backend
    ports:
      - '8000:8000'
    depends_on:
      - db
    volumes:
      - ./server:/usr/src/app

  # client:
  #   build:
  #     context: ./client
  #     dockerfile: Dockerfile
  #   container_name: chat-frontend
  #   platform: linux/amd64
  #   environment:
  #     - PORT=5741
  #   ports:
  #     - '5741:5741'
  #   depends_on:
  #     - server
  #   volumes:
  #     - ./client:/app

volumes:
  db_data:
