name: frontend-ci-cd

on: push

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.7

      - name: Move to client directory
        working-directory: client
        run: pwd

      - name: Install dependencies
        run: npm install

      - name: Lint
        run: npm run lint
